#!/usr/bin/env bash
# A Bash script that continuously displays "To infinity and beyond" every 2 seconds
# It prints "I am invincible!!!" when it receives a SIGTERM signal

# Define a function to handle SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done

# A Bash script that stops the 7-highlander process

pkill -f 7-highlander
