#!/usr/bin/env bash
# A Bash script that continuously displays "To infinity and beyond" every 2 seconds
# It prints "I am invincible!!!" immediately when it receives a SIGTERM signal

# Define a function to handle SIGTERM
trap 'printf "I am invincible!!!\n"; fflush' SIGTERM 2>/dev/null

while true
do
  echo "To infinity and beyond"
  sleep 2
done
